version: "3.9"

services:
  db:
    image: postgis/postgis:14-3.3
    container_name: study_db
    environment:
      POSTGRES_DB: studydb
      POSTGRES_USER: studyuser
      POSTGRES_PASSWORD: studypass
    ports:
      - "5432:5432"

  web:
    build:
      context: ./backend
    container_name: study_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_NAME: studydb
      POSTGRES_USER: studyuser
      POSTGRES_PASSWORD: studypass
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432